name: wf-cd-production
on:
  push:
    branches:
      - production
jobs:
  build-artifacts-production:
    runs-on: ubuntu latest
    steps:
      - name: Checkout Repo on Runner
        uses: actions/checkout@v4
        with:
          ref: "${{github.ref}}"
      - name: Create Build artifacts with parcel
        run: npx parcel build "./src/index.html" --dist-dir "./dist" --public-url "./dist"
      - name: Upload Build artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./dist"
          name: "build-artifact-production"

  deploy-artifacts-production:
    needs: "build-artifacts-production"
    runs-on: ubuntu latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: "production-env"
    steps:
      - name: Deploy artifacts on GH pages
        uses: actions/deploy-pages@v4
        with:
          artifact_name: "build-artifact-production"
          token: "${{github.token}}"
